REPETITIVE_INGREDIENTS = 'Дублирующиеся ингредиенты недопустимы'
REPETITIVE_TAGS = 'Дублирующиеся тэги недопустимы'
EMTY_INGREDIENTS = 'Пустой список ингредиентов недопустим'
EMTY_TAGS = 'Пустой список тэгов недопустим'
AMOUNT_INGREDIENTS = 'Кол-во ингредиента не может быть меньше 1'
FOLLOWING_ERROR = 'Подписка уже есть!'
SELF_FOLLOWING = 'Нельзя подписаться на самого себя!'
