volumes:
  media_foodgram:
  pg_data_foodgram:
  static_foodgram:

services:
  db:
    image: postgres:13.10
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    command: bash -c "
      python manage.py collectstatic --noinput &&
      cp -r /app/collected_static/. /backend_static/static/ &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py load_products /app/data/ingredients.json &&
      python manage.py load_tags /app/data/tags.json &&
      gunicorn --bind 0.0.0.0:8000 food_back.wsgi
      "
    depends_on:
      - db
    volumes:
      - static_foodgram:/backend_static
      - media_foodgram:/var/html/media/
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_foodgram:/static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static_foodgram:/staticfiles/
      - media_foodgram:/var/html/media/
    depends_on:
      - backend
