MAX_LENGTH_NAME = 100
MAX_LENGTH_SLUG = 80
MAX_LENGTH_INGRED = 10
MAX_LENGTH_TEXT = 256
MAX_COOKING_TIME = 240
MAX_LENGTH_LINK = 8
MAX_LENGTH_EMAIL = 256
LENGTH_USERNAME = 150
USERNAME_REGEX_TEXT = 'Имя может содержать только буквы, цифры и знаки .@+-_'
USERNAME_REGEX = r'^[\w.@+-]+$'
SELF_FOLLOWING = 'Нельзя подписаться на самого себя!'