MAX_LENGTH_NAME = 256
MAX_LENGTH_TAG_SLUG = 32
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_INGRED = 128
MAX_LENGTH_MEASUREMENT = 64
MAX_LENGTH_EMAIL = 254
LENGTH_USERNAME = 150
USERNAME_REGEX_TEXT = 'Имя может содержать только буквы, цифры и знаки .@+-_'
USERNAME_REGEX = r'^[\w.@+-]+$'
SELF_FOLLOWING = 'Нельзя подписаться на самого себя!'
MIN_COOKING_TIME = 1
MIN_AMOUNT = 1
RECIPE_NOT_FOUND = 'Рецепт не найден'
